twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

    globals:
        enterprise_name: '%app.enterprise_name%'

when@test:
    twig:
        strict_variables: true
