vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       applicant_resumes:
           uri_prefix: '%app.path.applicant_resumes%'
           upload_destination: '%kernel.project_dir%/public%app.path.applicant_resumes%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
